# Generated by Django 4.2.17 on 2024-12-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('image_link', models.URLField(blank=True)),
                ('video_link', models.URLField(blank=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
