# Generated by Django 4.2.17 on 2024-12-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufdrone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronesighting',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dronesighting',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dronesighting',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
